import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConvexClientProvider } from '@/components/providers/convex-provider';
import { ClerkProvider } from "@clerk/nextjs"
import "./globals.css";
import Asidebar from "./parts/aside";
import Navigationbar from "./parts/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ClerkProvider>
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}